[package]
name = "digital-duration-nom"
version = "0.2.0"
authors = ["Clifford T. Matthews <clifford.t.matthews@gmail.com>>"]
edition = "2018"

[dependencies]
nom = "6"
newtype_derive = "0.1.6"
custom_derive = "0.1.7"
